# Generated by Django 4.2 on 2023-05-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'required': 'Enter a valid phone number'}, max_length=15, unique=True),
        ),
    ]
