# Generated by Django 4.2 on 2023-05-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'invalid': 'Enter a valid phone number', 'required': 'Enter a valid phone number'}, max_length=15, unique=True),
        ),
    ]
