# Generated by Django 4.2 on 2023-05-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', models.CharField(max_length=15)),
                ('docs_image_url', models.URLField()),
                ('doc_type', models.CharField(max_length=55)),
            ],
        ),
    ]
